<a href="https://colab.research.google.com/github/KaveeshwaraBandara/Deep-learning-for-computer-vision-with-Python-and-TensorFlow/blob/main/Common_functions_in_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [ ]:
tensor_three_d = tf.constant([[[1,2,0],[3,5,-1]],[[10,2,0],[1,0,2]],[[5,8,0],[2,7,0]],[[2,1,9],[4,-3,32]]])
print(tensor_three_d.shape)

(4, 2, 3)


In [ ]:
print(tf.expand_dims(tensor_three_d,axis=0).shape)

(1, 4, 2, 3)


In [ ]:
x = tf.constant([2,3,4,5])
print(x.shape)
print(tf.expand_dims(x,axis=1))

(4,)
tf.Tensor(
[[2]
 [3]
 [4]
 [5]], shape=(4, 1), dtype=int32)


In [ ]:
x_expanded = tf.expand_dims(x,axis=0)
print(x_expanded,"\n")
x_squeezed = tf.squeeze(x_expanded,axis=0)
print(x_squeezed)

tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32) 

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.expand_dims(tensor_three_d,axis=3)
print(tensor_three_d.shape)
print(tf.reshape(tensor_three_d,[4,2,3]).shape)

(4, 2, 3, 1, 1, 1)
(4, 2, 3)


In [ ]:
tf.reshape(tensor_three_d,[24])

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  0,  3,  5, -1, 10,  2,  0,  1,  0,  2,  5,  8,  0,  2,  7,
        0,  2,  1,  9,  4, -3, 32], dtype=int32)>

In [ ]:
tf.reshape(tensor_three_d,[2,4,3])

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1],
        [10,  2,  0],
        [ 1,  0,  2]],

       [[ 5,  8,  0],
        [ 2,  7,  0],
        [ 2,  1,  9],
        [ 4, -3, 32]]], dtype=int32)>

In [ ]:
tf.reshape(tensor_three_d,[-1])

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  0,  3,  5, -1, 10,  2,  0,  1,  0,  2,  5,  8,  0,  2,  7,
        0,  2,  1,  9,  4, -3, 32], dtype=int32)>

In [ ]:
tf.reshape(tensor_three_d,[2,4,-1])

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1],
        [10,  2,  0],
        [ 1,  0,  2]],

       [[ 5,  8,  0],
        [ 2,  7,  0],
        [ 2,  1,  9],
        [ 4, -3, 32]]], dtype=int32)>

In [3]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
print(tf.constant(t1).shape,tf.constant(t2).shape)
t_row = tf.concat([t1, t2], axis=0)

print(t_row.shape)
print(t_row)

(2, 3) (2, 3)
(4, 3)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


In [ ]:
t_column = tf.concat([t1,t2], axis=1)
print(t_column)
print(t_column.shape)

tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)
(2, 6)


In [7]:
tf.stack([t1,t2,t1],axis=0)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]], dtype=int32)>

In [11]:
t_pad = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,], [2, 2]])
tf.pad(t_pad, paddings, "CONSTANT",constant_values=0)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [13]:
tf.pad(t_pad, paddings, "CONSTANT",constant_values=3)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 1, 2, 3, 3, 3],
       [3, 3, 4, 5, 6, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]], dtype=int32)>

In [14]:
paddings = tf.constant([[1, 2,], [3, 1]])
tf.pad(t_pad, paddings, "CONSTANT",constant_values=9)

<tf.Tensor: shape=(5, 7), dtype=int32, numpy=
array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 1, 2, 3, 9],
       [9, 9, 9, 4, 5, 6, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]], dtype=int32)>

In [16]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[1:4]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [17]:
tf.gather(params, [1,2,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [18]:
tf.gather(params, tf.range(1,4))

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [19]:
tf.gather(params, [0,5,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [26]:
params_2 = tf.constant([[0,1.0,2.0],[10.0,11.0,12.0],[20.0,21.0,22.0],[30.0,31.0,32.0]])
print(params_2.shape)
tf.gather(params_2, [0,2], axis=1)

(4, 3)


<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.,  2.],
       [10., 12.],
       [20., 22.],
       [30., 32.]], dtype=float32)>

In [30]:
indices = [[2,1]]
params_nd = [['a','b'],['c','d'],['e','f']]
tf.gather_nd(params_nd,indices)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'f'], dtype=object)>

In [32]:
tf.gather(params_nd,indices, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=string, numpy=
array([[[b'e', b'f'],
        [b'c', b'd']]], dtype=object)>