<a href="https://colab.research.google.com/github/KaveeshwaraBandara/Deep-learning-for-computer-vision-with-Python-and-TensorFlow/blob/main/Common_functions_in_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_three_d = tf.constant([[[1,2,0],[3,5,-1]],[[10,2,0],[1,0,2]],[[5,8,0],[2,7,0]],[[2,1,9],[4,-3,32]]])
print(tensor_three_d.shape)

(4, 2, 3)


In [3]:
print(tf.expand_dims(tensor_three_d,axis=0).shape)

(1, 4, 2, 3)


In [5]:
x = tf.constant([2,3,4,5])
print(x.shape)
print(tf.expand_dims(x,axis=1))

(4,)
tf.Tensor(
[[2]
 [3]
 [4]
 [5]], shape=(4, 1), dtype=int32)


In [7]:
x_expanded = tf.expand_dims(x,axis=0)
print(x_expanded,"\n")
x_squeezed = tf.squeeze(x_expanded,axis=0)
print(x_squeezed)

tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32) 

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [12]:
tensor_three_d = tf.expand_dims(tensor_three_d,axis=3)
print(tensor_three_d.shape)
print(tf.reshape(tensor_three_d,[4,2,3]).shape)

(4, 2, 3, 1, 1, 1)
(4, 2, 3)


In [13]:
tf.reshape(tensor_three_d,[24])

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  0,  3,  5, -1, 10,  2,  0,  1,  0,  2,  5,  8,  0,  2,  7,
        0,  2,  1,  9,  4, -3, 32], dtype=int32)>

In [14]:
tf.reshape(tensor_three_d,[2,4,3])

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1],
        [10,  2,  0],
        [ 1,  0,  2]],

       [[ 5,  8,  0],
        [ 2,  7,  0],
        [ 2,  1,  9],
        [ 4, -3, 32]]], dtype=int32)>

In [15]:
tf.reshape(tensor_three_d,[-1])

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  0,  3,  5, -1, 10,  2,  0,  1,  0,  2,  5,  8,  0,  2,  7,
        0,  2,  1,  9,  4, -3, 32], dtype=int32)>

In [16]:
tf.reshape(tensor_three_d,[2,4,-1])

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1],
        [10,  2,  0],
        [ 1,  0,  2]],

       [[ 5,  8,  0],
        [ 2,  7,  0],
        [ 2,  1,  9],
        [ 4, -3, 32]]], dtype=int32)>

In [20]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
print(tf.constant(t1).shape,tf.constant(t2).shape)
t_row = tf.concat([t1, t2], axis=0)

print(t_row.shape)
print(t_row)

(2, 3) (2, 3)
(4, 3)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


In [22]:
t_column = tf.concat([t1,t2], axis=1)
print(t_column)
print(t_column.shape)

tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)
(2, 6)
