<a href="https://colab.research.google.com/github/KaveeshwaraBandara/Deep-learning-for-computer-vision-with-Python-and-TensorFlow/blob/main/Deep_learning_FREECODECAMP_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import tensorflow as tf
import numpy as np

In [12]:
tensor_one_d = tf.constant([1,0,9,7], dtype=tf.int32)
print(tensor_one_d)
print(tensor_one_d.ndim)

tf.Tensor([1 0 9 7], shape=(4,), dtype=int32)
1


In [11]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]],
  dtype=tf.float32)
print(tensor_two_d)
print(tensor_two_d.ndim)

tf.Tensor(
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]], shape=(4, 3), dtype=float32)
2


In [13]:
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(casted_tensor_one_d)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [16]:
tensor_string = tf.constant(["hello world","hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [19]:
np_array = np.array([1,8,6,7])
print(np_array)

[1 8 6 7]


In [20]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 8 6 7], shape=(4,), dtype=int64)


In [26]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3,2],
    dtype=tf.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(3, 2, 5, 5), dtype=float32)


In [32]:
fill_tensor = tf.fill([3,4],5, name=None)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [34]:
ones_tensor = tf.ones([5,3,2], dtype=tf.float32,name=None)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [35]:
ones_like_tensor = tf.ones_like(fill_tensor,dtype=tf.int32,name=None)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [36]:
zeros_tensor = tf.zeros([3,2],dtype=tf.int32,name=None)
print(zeros_tensor)

tf.Tensor(
[[0 0]
 [0 0]
 [0 0]], shape=(3, 2), dtype=int32)


In [37]:
print(zeros_tensor.shape)
print(ones_like_tensor.shape)

(3, 2)
(3, 4)


In [38]:
print(tf.shape(zeros_tensor))

tf.Tensor([3 2], shape=(2,), dtype=int32)
