<a href="https://colab.research.google.com/github/KaveeshwaraBandara/Deep-learning-for-computer-vision-with-Python-and-TensorFlow/blob/main/Einsum_Operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [7]:
A = np.array([[2,6,5,2],
             [2,-2,2,3],
             [4,5,4,0]])

B = np.array([[2,9,0,3,0],
             [3,6,8,-2,2],
             [1,3,5,0,1],
             [3,0,2,0,5]])

print(A.shape)
print(B.shape)

print("\nMatmul C : \n")
print(np.matmul(A,B),"\n")

print("\nEinsum C : \n")
print(np.einsum("ij,jk->ik", A,B))

(3, 4)
(4, 5)

Matmul C : 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [27 78 60  2 14]] 


Einsum C : 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [27 78 60  2 14]]


In [12]:
C = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(C.shape, D.shape)

print("\nHardomond C : \n")
print(C*D, "\n")

print("\nEinsum C : \n")
print(np.einsum('ij,ij->ij', C,D))

(4, 3) (4, 3)

Hardomond C : 

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]] 


Einsum C : 

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]


In [18]:
print("\nTranspose of D : \n")
print(D.T)

print("\nTranspose of D using Einsum : \n")
print(np.einsum("ij->ji",D))


Transpose of D : 

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

Transpose of D using Einsum : 

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [21]:
E = np.array([[[2,6,5,2],[2,-2,2,3],[1,5,4,0]],[[1,3,1,22],[0,2,2,0],[1,5,4,1]]])
F = np.array([[[2,6,5,2,1],[2,-2,2,3,9],[1,5,4,0,7],[1,8,9,2,6]],[[1,3,1,22,7],[0,2,2,0,8],[1,5,4,1,7],[5,8,9,3,5]]])
print(E.shape, F.shape)

(2, 3, 4) (2, 4, 5)


In [22]:
print("Batch multiplication C : \n")
print(np.matmul(E,F), "\n")

print("Einsum C : \n")
print(np.einsum("bij,bjk->bik",E,F))

Batch multiplication C : 

[[[ 23  41  60  26 103]
  [  5  50  41   4  16]
  [ 16  16  31  17  74]]

 [[112 190 209  89 148]
  [  2  14  12   2  30]
  [ 10  41  36  29  80]]] 

Einsum C : 

[[[ 23  41  60  26 103]
  [  5  50  41   4  16]
  [ 16  16  31  17  74]]

 [[112 190 209  89 148]
  [  2  14  12   2  30]
  [ 10  41  36  29  80]]]


In [24]:
print("Sum : \n")
print(np.sum(E))

print("\nEinsum sum : \n")
print(np.einsum("bij->",E))

Sum : 

72

Einsum sum : 

72


In [28]:
A = np.array([[2,6,5,2],
             [2,-2,2,3],
             [4,5,4,0]])

print("Axis 0 Sum A = ")
print(np.sum(A,axis=0))
print("\nAxis 0 Sum using Einsum A = ")
print(np.einsum("ij->j",A))

Axis 0 Sum A = 
[ 8  9 11  5]

Axis 0 Sum using Einsum A = 
[ 8  9 11  5]


In [29]:
Q = np.random.randn(32,64,512)
K = np.random.randn(32,128,512)

In [30]:
print(np.einsum("bij,bmj->bim", Q,K))

[[[-19.44973242  10.40765011   8.46137566 ...  -0.47983591 -18.19351303
   -27.56632712]
  [  2.19330309   2.83500919 -28.54224011 ...  -2.09597055  24.44134675
    -7.17944391]
  [-17.34736069  17.21520486  27.60762079 ... -26.71083241  17.49745576
   -17.53477967]
  ...
  [-19.86745748  -9.03975351  22.31229299 ... -13.38019921   3.35235899
     0.28096703]
  [  6.20074176 -46.91973851  36.54490173 ...  31.59604059 -19.79623365
    21.21991163]
  [ -2.39912405  -4.47675783 -13.3050778  ... -43.53560696 -19.12585538
   -24.36450586]]

 [[ -6.16417645  16.385155    48.47851186 ...   8.71563597  10.40232818
     2.09299381]
  [  4.02346525  20.49645216 -25.61218362 ...  23.94862573  11.92702052
     3.37544875]
  [ -0.1121902  -31.75204971  12.03160726 ... -27.02427731  22.49354834
   -20.27751374]
  ...
  [ -8.2221944   57.62413985   7.60625521 ... -11.10830111 -16.58501089
    19.58394156]
  [  5.20431319 -21.48825795 -30.74713564 ...   6.79685274 -23.24068106
   -39.06085285]
  [-10.

In [31]:
print(np.einsum("bij,bmj->bim", Q,K).shape)

(32, 64, 128)


In [32]:
M = np.random.randn(2,4,4,2)
N = np.random.randn(2,4,4,1)

In [33]:
np.einsum("bcik,bcij->bckj", N,M).shape

(2, 4, 1, 2)