<a href="https://colab.research.google.com/github/KaveeshwaraBandara/Deep-learning-for-computer-vision-with-Python-and-TensorFlow/blob/main/LinearAlgebraOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
x_1 = tf.constant([[1,2,0],[3,5,-1]])
x_2 = tf.constant([[1,2,0],[3,5,-1],[4,5,6]])
tf.linalg.matmul(x_1,x_2,transpose_a=False,transpose_b=False,adjoint_a=False,adjoint_b=False,a_is_sparse=False,b_is_sparse=False,output_type=None,grad_a=False,grad_b=False,name=None)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)>

In [4]:
print(x_1@x_2)

tf.Tensor(
[[  7  12  -2]
 [ 14  26 -11]], shape=(2, 3), dtype=int32)


In [5]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]], dtype=int32)>

In [8]:
a = tf.constant([[[1,0],[3,-1],],[[10,0],[1,2]],[[5,0],[2,0]]])
b = tf.constant([[[5,1,4],[34,15,1],],[[1,2,2],[5,3,2]],[[2,2,3],[1,1,1]]])
print(a)
print(b)

tf.Tensor(
[[[ 1  0]
  [ 3 -1]]

 [[10  0]
  [ 1  2]]

 [[ 5  0]
  [ 2  0]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[ 5  1  4]
  [34 15  1]]

 [[ 1  2  2]
  [ 5  3  2]]

 [[ 2  2  3]
  [ 1  1  1]]], shape=(3, 2, 3), dtype=int32)


In [9]:
print(tf.linalg.matmul(a,b))

tf.Tensor(
[[[  5   1   4]
  [-19 -12  11]]

 [[ 10  20  20]
  [ 11   8   6]]

 [[ 10  10  15]
  [  4   4   6]]], shape=(3, 2, 3), dtype=int32)
