<a href="https://colab.research.google.com/github/KaveeshwaraBandara/Deep-learning-for-computer-vision-with-Python-and-TensorFlow/blob/main/sparseAndString_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
tensor_sparse = tf.sparse.SparseTensor(indices = [[1,1],[3,4]], values=[11,56], dense_shape=[5,6])
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [4]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [5]:
tensor_string = tf.constant(["hello", "i am","a string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [6]:
tf.strings.join(tensor_string, separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello+i am+a string'>