<a href="https://colab.research.google.com/github/KaveeshwaraBandara/Deep-learning-for-computer-vision-with-Python-and-TensorFlow/blob/main/TensorFlow_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [6]:
tensor_indexed = tf.constant([3,6,99,8,88,77,755])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:6])
print(tensor_indexed[3:])
print(tensor_indexed[0:5:2])

tf.Tensor([  3   6  99   8  88  77 755], shape=(7,), dtype=int32)
tf.Tensor([ 3  6 99  8], shape=(4,), dtype=int32)
tf.Tensor([ 6 99  8 88 77], shape=(5,), dtype=int32)
tf.Tensor([  8  88  77 755], shape=(4,), dtype=int32)
tf.Tensor([ 3 99 88], shape=(3,), dtype=int32)


In [19]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]],
  dtype=tf.int32)
"""print(tensor_two_d)"""
print(tensor_two_d[0:3,:])
print(tensor_two_d[0:3,0:2])
print(tensor_two_d[2,:])
print(tensor_two_d[:,0])
print(tensor_two_d[...,0])

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor([ 1  4  7 10], shape=(4,), dtype=int32)
tf.Tensor([ 1  4  7 10], shape=(4,), dtype=int32)
