<a href="https://colab.research.google.com/github/KaveeshwaraBandara/Deep-learning-for-computer-vision-with-Python-and-TensorFlow/blob/main/TensorsFlow_basics_and_casting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [ ]:
tensor_one_d = tf.constant([1,0,9,7], dtype=tf.int32)
print(tensor_one_d)
print(tensor_one_d.ndim)

tf.Tensor([1 0 9 7], shape=(4,), dtype=int32)
1


In [ ]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]],
  dtype=tf.float32)
print(tensor_two_d)
print(tensor_two_d.ndim)

tf.Tensor(
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]], shape=(4, 3), dtype=float32)
2


In [ ]:
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(casted_tensor_one_d)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["hello world","hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [ ]:
np_array = np.array([1,8,6,7])
print(np_array)

[1 8 6 7]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 8 6 7], shape=(4,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3,2],
    dtype=tf.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(3, 2, 5, 5), dtype=float32)


In [ ]:
fill_tensor = tf.fill([3,4],5, name=None)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones([5,3,2], dtype=tf.float32,name=None)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor,dtype=tf.int32,name=None)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros([3,2],dtype=tf.int32,name=None)
print(zeros_tensor)

tf.Tensor(
[[0 0]
 [0 0]
 [0 0]], shape=(3, 2), dtype=int32)


In [ ]:
print(zeros_tensor.shape)
print(ones_like_tensor.shape)

(3, 2)
(3, 4)


In [ ]:
print(tf.shape(zeros_tensor))

tf.Tensor([3 2], shape=(2,), dtype=int32)


In [ ]:
t = tf.constant([[[1,2,3],[2,2,3]],[[3,5,8],[9,7,5]]])
print(t)
tf.rank(t)

tf.Tensor(
[[[1 2 3]
  [2 2 3]]

 [[3 5 8]
  [9 7 5]]], shape=(2, 2, 3), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
t1 = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.size(t1)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [11]:
random_tensor = tf.random.normal([3,2],mean=100.0,stddev=1.0,dtype=tf.float32,seed=None,name=None)
print(random_tensor)

tf.Tensor(
[[101.27625   99.49079 ]
 [ 99.716484  98.916016]
 [100.09598  100.57023 ]], shape=(3, 2), dtype=float32)


In [15]:
random_tensor_uniform = tf.random.uniform([5,5],minval=0,maxval=1000,dtype=tf.int32,seed=None,name=None)
print(random_tensor_uniform)

tf.Tensor(
[[172 798 946 246 360]
 [640 455 928 346 140]
 [157 144 538 412 912]
 [507 498 329 118 976]
 [455 814 426 584 984]], shape=(5, 5), dtype=int32)
