<a href="https://colab.research.google.com/github/KaveeshwaraBandara/Deep-learning-for-computer-vision-with-Python-and-TensorFlow/blob/main/TensorFlow_Maths_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
x_abs = tf.constant([-2.25,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [3]:
# complex number
x_complex = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x_complex)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [5]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [8]:
x_1 = tf.constant([1,2,3,4,5,6],dtype=tf.int32)
x_2 = tf.constant([1,2,3,4,5,6],dtype=tf.int32)
print(tf.add(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.divide(x_1,x_2))

tf.Tensor([ 2  4  6  8 10 12], shape=(6,), dtype=int32)
tf.Tensor([0 0 0 0 0 0], shape=(6,), dtype=int32)
tf.Tensor([ 1  4  9 16 25 36], shape=(6,), dtype=int32)
tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float64)


In [11]:
x_3 = tf.constant([1,2,3,4,5,6],dtype=tf.float32)
x_4 = tf.constant([1,2,3,0,5,6],dtype=tf.float32)
print(tf.math.divide_no_nan(x_3,x_4))

tf.Tensor([1. 1. 1. 0. 1. 1.], shape=(6,), dtype=float32)


In [12]:
x_5 = tf.constant([[5,3,6,6,4,6],],dtype=tf.int32)
x_6 = tf.constant([[7],[5],[3]],dtype=tf.int32)
print(x_5.shape)
print(x_6.shape)
print(tf.math.multiply(x_5,x_6))

(1, 6)
(3, 1)
tf.Tensor(
[[35 21 42 42 28 42]
 [25 15 30 30 20 30]
 [15  9 18 18 12 18]], shape=(3, 6), dtype=int32)


In [13]:
a = tf.constant([0., 0., 0., 0.])
b = tf.constant([-2., 0., 2., 5.])
tf.math.maximum(a, b)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [14]:
a_1 = tf.constant([-5., 0., 0., 0.])
b_1 = tf.constant([-3.])
tf.math.maximum(a_1, b_1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  0.,  0.], dtype=float32)>

In [21]:
B = tf.constant([ [2, 20, 30, 3, 6],
                  [3, 11, 16, 1, 8],
                  [14, 45, 23, 5, 27]])
tf.math.argmax(B, axis=0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>

In [22]:
tf.math.argmin(B, axis=1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 3, 3])>

In [23]:
x = tf.constant([2, 4])
y = tf.constant(2)
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [24]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [26]:
tf.pow(tf.constant(2),tf.constant(5))

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [27]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]],
  dtype=tf.float32)

In [32]:
print(tf.math.reduce_sum(
    tensor_two_d, axis=1, keepdims=False, name=None
))

tf.Tensor([ 6. 15. 24. 33.], shape=(4,), dtype=float32)


In [33]:
print(tf.math.reduce_max(
    tensor_two_d, axis=0, keepdims=False, name=None
))

tf.Tensor([10. 11. 12.], shape=(3,), dtype=float32)


In [38]:
tf.math.top_k(tensor_two_d,k=1)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 3.],
       [ 6.],
       [ 9.],
       [12.]], dtype=float32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2],
       [2]], dtype=int32)>)